# Generated by Django 5.0.6 on 2024-06-26 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(db_column='idgenero', primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=20)),
                ('apellido_cliente', models.CharField(max_length=20)),
                ('numero_cliente', models.CharField(max_length=20)),
                ('correo_cliente', models.CharField(max_length=20)),
                ('ciudad_cliente', models.CharField(max_length=20)),
                ('id_genero', models.ForeignKey(db_column='idgenero', on_delete=django.db.models.deletion.CASCADE, to='encuentroVerde.genero')),
            ],
        ),
    ]
