# Generated by Django 5.0.6 on 2024-06-27 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuentroVerde', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parque',
            fields=[
                ('id_parque', models.AutoField(db_column='idparque', primary_key=True, serialize=False)),
                ('Parque', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='formulario',
            name='id_parque',
            field=models.ForeignKey(db_column='id_parque', default=1, on_delete=django.db.models.deletion.CASCADE, to='encuentroVerde.parque'),
            preserve_default=False,
        ),
    ]
